In [1]:
!pip install numpy

In [21]:
import numpy as np

# Creating Numpy Arrays


### np.array()

In [22]:
list1=[1,2,3,4,5]
print(type(list1))
array1=np.array(list1)
print(array1)
print(type(array1))
print(array1.ndim)

<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [23]:
list2=[[1,2],[3,4]]
array2=np.array(list2)
print(array2)
print(type(array2))
print(array2.ndim)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2


### np.zeros()

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### np.ones()

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones((2,3,4)) #2=block,3=row,4=column

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [28]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### np.full()

In [29]:
np.full(5,-2)

array([-2, -2, -2, -2, -2])

In [30]:
np.full((2,3),-2)

array([[-2, -2, -2],
       [-2, -2, -2]])

In [31]:
np.full((2,2,3),-2)

array([[[-2, -2, -2],
        [-2, -2, -2]],

       [[-2, -2, -2],
        [-2, -2, -2]]])

### np.arange()

In [32]:
# np.array(range(start,stop,step))
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(2,10,3)

array([2, 5, 8])

### np.linspace()

In [35]:
# np.linspace(start,stop,no. of elements in between)
np.linspace(1,10,2)

array([ 1., 10.])

In [36]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [37]:
np.linspace((1,2),(5,10),5)

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.]])

### np.diag()

In [38]:
np.diag([2,3,4,5])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [47]:
np.diag([2,3,4,5],k=-1)

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0]])

### np.eye()

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### np.identity(

In [49]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.random.rand()


In [61]:
np.random.rand(2,3)

array([[0.09300842, 0.64526055, 0.90495121],
       [0.96957227, 0.53034976, 0.71195656]])

In [67]:
np.random.rand(2,2,2,3)

array([[[[0.93526365, 0.91580457, 0.29397123],
         [0.0359165 , 0.56566524, 0.39165091]],

        [[0.47558468, 0.58755031, 0.42153994],
         [0.65370665, 0.3451073 , 0.99666172]]],


       [[[0.2849661 , 0.74446926, 0.72826346],
         [0.03962465, 0.83473291, 0.87009243]],

        [[0.09514797, 0.63575045, 0.85051898],
         [0.89869812, 0.7005448 , 0.56885686]]]])

### np.random.randint()

In [71]:
np.random.randint(2,6,size=(2,6))

array([[3, 4, 4, 3, 3, 2],
       [3, 5, 3, 4, 4, 4]])

1D Array:```array_name[idx] (similar to Python list)```

2D Array: ```array_name [row,col_idx](similar to matrix)```

3D Array: array_name[dim1_idx, dim2_idx,...dimN_idx]


In [74]:
list1=[1,2,3,4,5]


In [79]:
list1[2]

3

In [76]:
array1=np.array(list1)

In [80]:
array1[2]

3

### Multi Dimensional

In [81]:
list2=[[1,2,3,4,5],[1,3,5,7,8]]

In [91]:
list2[0][1] #0=represent first block, 1=element of that block

2

In [92]:
array2=np.array(list2) #array maa pani access garnu sakiyo

In [93]:
array2[0][1]

2

In [95]:
array2

array([[1, 2, 3, 4, 5],
       [1, 3, 5, 7, 8]])

In [101]:
array2[0,1] # 0=block of matrix,1=element of that block

2

In [102]:
array2[1,3] # 1=seond block of matrix,3=element of that block

7