In [1]:
import numpy as np

In [4]:
a=np.array([[1,2,3],[4,5,6]])

In [7]:
a.shape #attributes


(2, 3)

In [30]:
a.dtype

dtype('int32')

In [31]:
a.ndim

2

In [32]:
a.flatten() # convert multi dimension to single dim

array([1, 2, 3, 4, 5, 6])

In [33]:
a.sum()

21

In [34]:
a.max()

6

In [35]:
a.max(axis=0)
# element compare between columnwise respective cell

array([4, 5, 6])

In [36]:
a.max(axis=1)
# each cell row wise element has compared

array([3, 6])

In [39]:
a.argmax(axis=1)

array([2, 2], dtype=int64)

In [51]:
a.shape

(2, 3)

In [53]:
#Notice: product of element should be conserved
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
b=a.reshape((1,2,3))

In [57]:
b.shape

(1, 2, 3)

In [61]:
m=np.array([[1,2],[3,4]])
n=np.array([[5,6],[7,8]])

In [73]:
np.concatenate((m,n),axis=None)
#flattened in multi Dim like 2D flatted
#no column and no row are preserved simply data are flatted

array([1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
np.concatenate((m,n),axis=0) 
#column must be same as each cell

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [75]:
np.concatenate((m,n),axis=1) 
#row must be same as each cell in Dim

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Split

In [83]:
string='hello how are you?'


In [85]:
string.split(' ')
#by default it takes space i.e string.split()
#is also correct

['hello', 'how', 'are', 'you?']

In [79]:
a=a.reshape((6))

In [77]:
a

array([1, 2, 3, 4, 5, 6])

In [94]:
np.split(a,3)
#3= total three parts needed

[array([1, 2]), array([3, 4]), array([5, 6])]

In [98]:
np.split(a,[2,5,7])
#split when it rech inmindex 2 , 5,and 7 respectively

[array([1, 2]), array([3, 4, 5]), array([6]), array([], dtype=int32)]