- bool: Boolean(True or False) stored as a byte.
- int8, int16, int32, int64: Integer with a specific number of bits (8,16,32, or 64
- uint8, uint16, uint32, uint64: Unsigned intger with a specific number  of bits (8,16,32 or 64)
- float16, float32, float64:  Floating-point number with a specific precision(half, single, or double precision).

- complex64, complex128: Complex number with a specific precision( single or double precision).

In [5]:
import numpy as np
a=np.array([1,2,3],dtype=np.int32)
b=np.array([1.0,2.0,3.0],dtype=np.float64)
c=np.array([True,False,True],dtype=np.bool_)

print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
bool


In [6]:
d=np.array([1,2,3],dtype=np.float64)
d

array([1., 2., 3.])

In [7]:
e=np.array([1.0,2.0,3.0],dtype=np.int32)
e

array([1, 2, 3])

In [8]:
f=np.array([True,False,True],dtype=np.int32)
f

array([1, 0, 1])

In [9]:
g=a.astype(np.float32)

In [10]:
g

array([1., 2., 3.], dtype=float32)