In [1]:
import numpy as np


### 1. Elementary Operations

In [3]:
a=np.array([[4,5,6],[5,7,9]])
b=np.array([[1,2,3],[9,8,7]])

In [4]:
a

array([[4, 5, 6],
       [5, 7, 9]])

In [5]:
b


array([[1, 2, 3],
       [9, 8, 7]])

In [8]:
a+b 
#elementwise operation on respective postion of matrix

array([[ 5,  7,  9],
       [14, 15, 16]])

###  Operations

#### Airthmetic opertaions:

- np.add()
- np.subtract()
- np.multyply()
- np.divide()
- np.floor_division() or // 
- np.remainder() or np.divmod()
- np.absoulute()
- np.sqrt()
- np.square()
- np.power()
- np.sign() : Apply sign function

#### Trigonometric functions:

- np.sin()
- np.cos()
- np.tan()

#### Hyperbolic funtions:

 - np.sinh()
 - np.cosh()
 - np.tanh()
 

#### Rounding Functions:
- np.around(): Round to the given number of decimal evenly 
- np.round():ROund to the given number of decimal
- np.rint(): Round to the neares integer
- np.fix(): Round to nearest interger towards zero
- np.floor(): 
- np.ceil():


#### Exponents and Logarithms:
- np.exp()
- np.exmp1(): Compute 'exp(x)-1' with greater precision for small values 
- np.exp2(): compute '2**p for all elements p in the array
- np.log(): Compute elemetn-wise natural logarithm
- np.log10():  compute elementwise base 10 logarithm
- np.log2(): compute elementwise base 2 logarithm

### 2. Matrix Operations

In [30]:
a=np.array([[4,5],[3,7]])
b=np.array([[1,2],[9,8]])

In [31]:
a

array([[4, 5],
       [3, 7]])

In [32]:
b

array([[1, 2],
       [9, 8]])

In [33]:
np.dot(a,b)

array([[49, 48],
       [66, 62]])

In [34]:
c=np.array([[4,5,6],[5,7,9]])
d=np.array([[1,2],[8,7]])

In [35]:
np.dot(c,d)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [36]:
np.dot(d,c)

array([[ 14,  19,  24],
       [ 67,  89, 111]])

#### Transpose matrix

In [37]:
np.transpose(a)

array([[4, 3],
       [5, 7]])

In [40]:
np.trace(a)
#sum of diagonal element

11

In [42]:
np.linalg.det(a)
#determinant of a

13.0

In [43]:
d=np.random.rand(2,3)

In [44]:
d.shape

(2, 3)

In [47]:
np.linalg.det(d)

LinAlgError: Last 2 dimensions of the array must be square

In [49]:
np.linalg.inv(a)
# inverse of a

array([[ 0.53846154, -0.38461538],
       [-0.23076923,  0.30769231]])

In [52]:
np.linalg.eig(a)
# eigen value and vector

(array([1.34668807, 9.65331193]),
 array([[-0.88333068, -0.66249905],
        [ 0.46875037, -0.74906275]]))

In [56]:
a=[[1,2],[2,3]]
b=[1,2]
# Ax=b type solve value of x

In [57]:
np.linalg.solve(a,b)

array([1., 0.])

#### Broadcasting

In [59]:
a=np.array([[1,2],[3,4]])
b=np.array([10,20])

In [60]:
a

array([[1, 2],
       [3, 4]])

In [61]:
b

array([10, 20])

In [63]:
a+b

array([[11, 22],
       [13, 24]])

### Why Numpy over python's for loop

In [10]:
import numpy as np
import time
# using NumPy for element wise multiplications
a=np.random.rand(100000)
b=np.random.rand(100000)

start =time.time()
c=a*b
end=time.time()
numpy_execution_time=end-start
print("time taken by Numpy for loop: {:.6f} seconds".format(numpy_execution_time))

#Using Pythong for loop elemen-wise multiplication
a=list(a)
b=list(b)
c=[]

start =time.time()
for i in range(len(a)):
    c.append(a[i]*b[i])
end=time.time()
for_loop_execution_time=end-start
print("time taken by python for loop: {:.6f} seconds".format(end-start))

print(f'NumPy is {int(for_loop_execution_time/numpy_execution_time)}times faster than python')
 

time taken by Numpy for loop: 0.003006 seconds
time taken by python for loop: 0.058777 seconds
NumPy is 19times faster than python
