In [16]:
import numpy as np

1D Array:```array_name[idx] (similar to Python list)```

2D Array: ```array_name [row,col_idx](similar to matrix)```

3D Array: `array_name[dim1_idx, dim2_idx,...dimN_idx]`


### One Dimensional Array

In [17]:
list1=[1,2,3,4,5,6,7,8]

In [18]:
list1[1:3]

[2, 3]

In [19]:
 array1=np.array(list1)

In [20]:
array1[1:7:2]

array([2, 4, 6])

### Two Dimensional array

In [21]:
list2=[[1,2,3,4,5,6,7,8],[1,3,5,7,9,11,13,15]]

In [22]:
list2[0][5:]

[6, 7, 8]

In [23]:
array2=np.array(list2)

In [24]:
array2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

In [25]:
array2[0][5:] #0=first block of matrix list, 5:= element from 5th to last


array([6, 7, 8])

In [26]:
array2[0,5:]

array([6, 7, 8])

In [27]:
array2[:,1:4] #:=both block 1:4= element from 1 to 4th

array([[2, 3, 4],
       [3, 5, 7]])

In [28]:
array2[0][1:8:2]

array([2, 4, 6, 8])

In [41]:
# [start : stop : step]
array2[:,1::2] # :=all block, 1::=start from 1 to last and step is 2

array([[ 2,  4,  6,  8],
       [ 3,  7, 11, 15]])

### Multi Dimensional

In [42]:
list3=[[1,2,3,4,5,6,7,8],[1,3,5,7,9,11,13,15],[15,20,25,45,60,17,18,89]]

In [43]:
array3=np.array(list3)

In [44]:
array3

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  3,  5,  7,  9, 11, 13, 15],
       [15, 20, 25, 45, 60, 17, 18, 89]])

In [45]:
array3[1:, 4:7:1] 
# 1:= 2nd block to last block ,
#4:7:1= from 4 to 7th element with step 1

array([[ 9, 11, 13],
       [60, 17, 18]])

In [47]:
array3.shape

(3, 8)

In [48]:
array3.shape[0]

3

In [52]:
list4=[[[1,2,3,4],[5,6,7,8]],
      [[1,4,5,7],[9,10,11,12]],
       [[5,10,15,20],[12,17,20,25]]
      ]

In [53]:
array4=np.array(list4)

In [54]:
array4.shape

(3, 2, 4)

In [56]:
array4.ndim

3

In [57]:
array4[:2, :, 1:3]

array([[[ 2,  3],
        [ 6,  7]],

       [[ 4,  5],
        [10, 11]]])